### PR TITLE
3 small fixes in Pdf-module

### PR DESCRIPTION
**Pull request by hak223sve**
1. Better handling Pdf-files where image heigth and width are PdfIndirectObjects
2. Better handling of Pdf-files with "empty" hex strings
3. Better handling of Pdf-files where form-fields are PdfIndirectObjects

### CODE REVIEW

**Comment by smmorrissey** [comment]
Sheila +1

**Comment by pmay** [comment]
+1

**Comment by asciim0** [comment]
+1

**Comment by tledoux** [comment]
+1

**Comment by chhkb** [comment]
Christen, KBDB +1

**Comment by friesey** [comment]
Yvonne Goportis +1

**Comment by carlwilson** [comment]
Fixed by #188

**Pull request closed without merging**
