### PR TITLE
[Travis] add basic Travis file

### PR DESCRIPTION
**Pull request by willp-bl**

### CODE REVIEW

**Comment by gmcgath** [comment]
Travis is something new to me. I've found some pages explaining how to do things with it, but don't understand its basic purpose. Could you point me at something or explain?

**Comment by willp-bl** [comment]
It's a free continuous integration service that runs after every commit to the repository.  It compiles the code and runs any unit tests.  Build/test failures are then notified immediately.  A build status icon can then be shown in a readme or website, see: https://github.com/openplanets/nanite/blob/master/README.md

To enable you just need to log in to https://travis-ci.org/ using your github account and enable it for the jhove repository.  Plus have a travis settings file, like this one.

**Comment by willp-bl** [comment]
See the widget in the readme in my branch now - if you merge you might want to change it to match your repository

**Comment by carlwilson** [comment]
Closing this PR as Travis build now part of OPF CI cycle.

**Pull request closed without merging**
