### PR TITLE
Fix for #531

### LINKED ISSUE #531: PDF-hul: Error ID possibly not shown for "Size entry missing in trailer dictionary" error
In the attached sample file, the error output for PDF-hul error "Size entry missing in trailer dictionary" error does not display the error ID in the output. However, the file also contains a "Validation ended prematurely due to an unhandled exception." error - I am not sure if the error ID was simply not assigned due the thrown unhandled error. The output is: 

(...)
  Size: 628
  Format: PDF
  Status: Unknown
  SignatureMatches:
   PDF-hul
  ErrorMessage: Size entry missing in trailer dictionary
   Offset: 607
  ErrorMessage: Validation ended prematurely due to an unhandled exception.
  MIMEtype: application/pdf
(...)

The according file is attached.

[T04_015_trailer-no-size-key-value-pair.pdf](https://github.com/openpreserve/jhove/files/3885276/T04_015_trailer-no-size-key-value-pair.pdf)

### PR DESCRIPTION
**Pull request by samalloing**
Hi @carlwilson 

This pull request fixes #531 : because the Size keyword didn't exist the trailer wasn't parsed completly and some variable where null. So I did some changes so the variables are not null, because these lines are never reached
_xref: https://github.com/openpreserve/jhove/blob/de1f5fd8427a0e8365b44ec095e34bf4d2cde8ad/jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java#L1325
_docCatDictRef: https://github.com/openpreserve/jhove/blob/de1f5fd8427a0e8365b44ec095e34bf4d2cde8ad/jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java#L1339

I don't know my java code is up to your standards. Just give feedback so I can fix it.
I also left some debug code that's why there are 3 commits instead of one. sorry for the mess.

Sam

### CODE REVIEW

**Comment by carlwilson** [comment]
FYI @samalloing I cheat with my commits and squash them before pushing ;)

**Review by carlwilson — APPROVED** [review]
That's perfect and neat, I see the problem, good catch.

**Comment by carlwilson** [comment]
Hi @samalloing, this has broken the Travis tests, but it's not your problem; it's mine. I need to update the results to patch for the file you've fixed (it's expecting a broken result). I'll add a PR so you can see what I've done soon but going to merge PRs that offer less resistance first ;)

**Comment by MartinSpeller** [comment]
[PDF-hul: Error ID possibly not shown for "Size entry missing in trailer dictionary" error #531 - Assigned to Sam Alloing samalloing](https://trello.com/c/w9Md1pr7/38-pdf-hul-error-id-possibly-not-shown-for-size-entry-missing-in-trailer-dictionary-error-531-assigned-to-sam-alloing-samalloing)

**Comment by carlwilson** [comment]
Hi, @samalloing I've looked at the integration test results, and it's all good. I thought I'd just give you an illustration of what the issue is. The Black Box Tester takes the dev version of JHOVE and compares the output results across a corpus of files to the same from the last release version. I thought I'd share the results with you. The output for one of the PDF files has changed, it's from the [PDF regression corpus](https://github.com/openpreserve/jhove/blob/integration/test-root/corpora/regression/modules/PDF-hul/pdf-hul-40-61501688X.pdf). If you know what you're looking for you can see the error in the Travis build here: https://travis-ci.org/github/openpreserve/jhove/jobs/684211706#L7866. The 1.24 results look like:

```xml
 <repInfo uri="./test-root/corpora/regression/modules/PDF-hul/pdf-hul-40-61501688X.pdf">
  <reportingModule release="1.12.2" date="2019-12-10">PDF-hul</reportingModule>
  <lastModified>2019-07-03T04:23:17+01:00</lastModified>
  <size>355787</size>
  <format>PDF</format>
  <version>1.6</version>
  <status>Not well-formed</status>
  <sigMatch>
  <module>PDF-hul</module>
  </sigMatch>
  <messages>
   <message offset="325756" severity="error" id="PDF-HUL-110">Invalid object number or object stream</message>
  </messages>
  <mimeType>application/pdf</mimeType>
  ...
```
Post your fix it looks like this:
```xml
 <repInfo uri="./test-root/corpora/regression/modules/PDF-hul/pdf-hul-40-61501688X.pdf">
  <reportingModule release="1.12.2" date="2019-12-10">PDF-hul</reportingModule>
  <lastModified>2019-07-03T04:23:17+01:00</lastModified>
  <size>355787</size>
  <format>PDF</format>
  <version>1.6</version>
  <status>Well-Formed and valid</status>
  <sigMatch>
  <module>PDF-hul</module>
  </sigMatch>
  <mimeType>application/pdf</mimeType>
  <profiles>
   <profile>Linearized PDF</profile>
  </profiles>
  <properties>
...
```
I need to patch the expected results to expect that now :)

**Comment by carlwilson** [comment]
@samalloing if you'd care to review #590 this has the patch for the integration tests. Once that's merged this will pass on Travis :)

**Comment by samalloing** [comment]
Hi @carlwilson,

I investigated this a little bit more and I think I know what is going on with the travis build on file pdf-hul-40-61501688X.pdf. The problem is not the error that was reported on this file PDF-HUL-110. It was actually PDF-HUL-64 that was reported but that was only shown in the log messages if you ask to print the messages (I notice this more that error get swallowed up by other errors and masking the real issue). Anyway this wasn't the real issue either. It was when  But still that was not the real issue. It was with processing of the bookmarks (I think it is called that) there is Literal processing going on there and it showed the same problem as is discussed in this PR/issue 277. The processing goes beyond the boundaries because of a character and the processing stops but for some reason (I didn't look into this) there is a null Keyword created. The null Keyword is creating the PDF-HUL-110 issue. But the real issue is the processing of the literals that go wrong. So by solving this issue 277 the processing happens as normal and no extra null Keyword is created. So there for the document becomes valid.

I hope my explanation is clear and explains more or less why this document became valid and well formed after this issue is solved.

Sam

**Pull request merged**
