### PR TITLE
Extension level support added

### PR DESCRIPTION
**Pull request by samalloing**
Hi @carlwilson 

As discussed I created code for parsing the Extension Level information in a PDF. According to https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/adobe_supplement_iso32000.pdf a pdf can have Extensions. This code prints out which extension level a PDF supports and also the vendor of the extension.
Also check if the information appears in the right location of the output. I think the code is in a good spot, but I'm not sure if the output is. I didn't change anything in the output, this is the default location.

Sam

### CODE REVIEW

**Comment by samalloing** [comment]
I'll also add a test file to the Error wiki if this pull request is fine

**Comment by samalloing** [comment]
Hi @carlwilson ,

Will this be integrated in the main branch (Integration)? 

Sam

**Comment by carlwilson** [comment]
Sorry @samalloing it now is and the RC will be out tomorrow ABW

**Comment by samalloing** [comment]
Hi @carlwilson , I still don't see the PREFIXNAMESREGISTY in PDFStrings.java in the main (integration) branch

**Comment by carlwilson** [comment]
I can see the issue, it's a Russian doll PR as it were. Will be taking a look over what's a long holiday weekend in the UK, resolved for next week

**Pull request merged**
