### PR TITLE
Ignoring a comment in annotations

### PR DESCRIPTION
**Pull request by samalloing**
Hi @carlwilson 

I don't know if this is useful, but I encountered a number of these. This pull request is only for a comment in Annotations. When a comment is encountered the pdf generates an error.

Sam

### CODE REVIEW

**Review by carlwilson — APPROVED** [review]

**Comment by carlwilson** [comment]
I may be missing something here @samalloing. I'm currently merging what I can for a very imminent 1.26 release candidate. This PR doesn't seem to build as it's missing a [`Comment` class](https://github.com/openpreserve/jhove/runs/5859849045?check_suite_focus=true#step:4:1414). Care to comment ;)

**Comment by samalloing** [comment]
Hi Carl,

import edu.harvard.hul.ois.jhove.module.pdf.Comment; should be added. It is the existing Comment class

Sorry about that. Do you want me to update the pull request?

Sam

**Comment by carlwilson** [comment]
> Sorry about that. Do you want me to update the pull request?

If you could please, it makes it easier for me to review and merge if I'm not an author. Thanks, I will pick it up if you can't though so worry not.

Thanks @samalloing

**Comment by samalloing** [comment]
Hi Carl,

I updated the pull request. It should work now

Sam

**Review by MaximPlusov — APPROVED** [review]

**Pull request merged**
