### PR TITLE
Updated audio outputs to conform to the AES57-2011 spec

### LINKED ISSUE #111: Use of xsi:type in AES output
## Dev Effort

1D

## Description

Both the WAVE and AIFF modules embed audio metadata in AES format without providing a schema. One of the produced elements make use of `xsi:type, <tcf:filmFraming tcf:framing="NOT_APPLICABLE" xsi:type="tcf:ntscFilmFramingType"/>`. 

Because JHOVE schema does not validate embedded xml (`processContents="skip"`), the use of `xsi:type` does not cause problem. However, METS & PREMIS schema will validate embedded xml if sufficient definition is available (`processContents="lax"`). 

When we import this element into PREMIS document, it is not valid because `xsi:type` references a Type Definition (`http://www.w3.org/TR/xmlschema-1/#xsi_type`), thus explicit assertion of type validation is attempted. 

The type `tcf:ntscFilmFramingType` cannot be resolved and causes validation to fail.
Looking into aes.org, we cannot find a schema describing the element in the namespace: http://www.aes.org/tcf. 

It appears the AES X098B schema is not publicly available yet (according to Gary).

### LINKED ISSUE #362: AES output does not conform to the AES57-2011 spec
JHOVE's AES output was written based on the beta spec, and does not conform to the final AES57-2011 spec. More details and a merge request to address the problem can be found here: https://github.com/openpreserve/jhove/pull/357.

## Dev Effort
2D

## Description
The AES output that JHOVE currently generates does not conform to the AES57-2011 spec. The schema can be found [here](https://www.loc.gov/standards/amdvmd/audiovideoMDschemas.html).

This commit updates JHOVE to produce a valid AES57-2011 document. The bulk of the changes are related to how times and durations are reported. The original code generated a structure like this:
```xml
<tcf:duration tcf:frameCount="30" tcf:timeBase="1000" tcf:videoField="FIELD_1" tcf:countingMode="NTSC_NON_DROP_FRAME">
  <tcf:hours>0</tcf:hours>
  <tcf:minutes>0</tcf:minutes>
  <tcf:seconds>12</tcf:seconds>
  <tcf:frames>29</tcf:frames>
  <tcf:samples tcf:sampleRate="S44100">
    <tcf:numberOfSamples>121</tcf:numberOfSamples>
  </tcf:samples>
  <tcf:filmFraming tcf:framing="NOT_APPLICABLE" xsi:type="tcf:ntscFilmFramingType"/>
</tcf:duration>
```
The same information is now represented like this:
```xml
<aes:duration editRate="44100" factorNumerator="1" factorDenominator="1">571951</aes:duration>
```
Another change affects the "channelAssignment" element. This element does not have a "mapLocation" attribute, as the current code adds. Instead, AES57-2011 uses two new attributes "leftRightPostion" and "frontRearPosition". Detailed descriptions of this attributes can be found on [this page](https://rucore.libraries.rutgers.edu/open/projects/openwms/index.php?sec=guides&sub=metadata&pg=t_sound-qual). I could not determine a way to map all of the possible JHOVE "mapLocations" to the new AES attributes (for example, what does "SURROUND" mean?), so I decided to leave them out rather than include potentially inaccurate data.

(As an aside, I suspect that the way that JHOVE is currently mapping channel location for 4-channel AIFF audio is incorrect. [Per spec](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Docs/AIFF-1.3.pdf), it should be LEFT, CENTER, RIGHT, SURROUND. JHOVE maps it as LEFT, RIGHT, CENTER, SURROUND.)

### PR DESCRIPTION
**Pull request by pwinckles**
The AES output that JHOVE currently generates does not conform to the AES57-2011 spec. The schema can be found [here](https://www.loc.gov/standards/amdvmd/audiovideoMDschemas.html).

This commit updates JHOVE to produce a valid AES57-2011 document. The bulk of the changes are related to how times and durations are reported. The original code generated a structure like this:
```xml
<tcf:duration tcf:frameCount="30" tcf:timeBase="1000" tcf:videoField="FIELD_1" tcf:countingMode="NTSC_NON_DROP_FRAME">
  <tcf:hours>0</tcf:hours>
  <tcf:minutes>0</tcf:minutes>
  <tcf:seconds>12</tcf:seconds>
  <tcf:frames>29</tcf:frames>
  <tcf:samples tcf:sampleRate="S44100">
    <tcf:numberOfSamples>121</tcf:numberOfSamples>
  </tcf:samples>
  <tcf:filmFraming tcf:framing="NOT_APPLICABLE" xsi:type="tcf:ntscFilmFramingType"/>
</tcf:duration>
```
The same information is now represented like this:
```xml
<aes:duration editRate="44100" factorNumerator="1" factorDenominator="1">571951</aes:duration>
```
Another change affects the "channelAssignment" element. This element does not have a "mapLocation" attribute, as the current code adds. Instead, AES57-2011 uses two new attributes "leftRightPostion" and "frontRearPosition". Detailed descriptions of this attributes can be found on [this page](https://rucore.libraries.rutgers.edu/open/projects/openwms/index.php?sec=guides&sub=metadata&pg=t_sound-qual). I could not determine a way to map all of the possible JHOVE "mapLocations" to the new AES attributes (for example, what does "SURROUND" mean?), so I decided to leave them out rather than include potentially inaccurate data.

(As an aside, I suspect that the way that JHOVE is currently mapping channel location for 4-channel AIFF audio is incorrect. [Per spec](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Docs/AIFF-1.3.pdf), it should be LEFT, CENTER, RIGHT, SURROUND. JHOVE maps it as LEFT, RIGHT, CENTER, SURROUND.)

Fixes #362 #367

### CODE REVIEW

**Comment by pwinckles** [comment]
I see that the Travis-CI build is failing. As far as I can tell, the job it's running is comparing the XML output of previous JHOVE versions against the output of these changes. The output is necessarily different, which causes the build to fail.

**Comment by MartinSpeller** [comment]
[Use of xsi:type in AES output #111 - Assigned to ross-spencer](https://trello.com/c/xGn2Y9hg/7-use-of-xsitype-in-aes-output-111-assigned-to-ross-spencer)

**Comment by carlwilson** [comment]
FYI @deanforsmith the above conflicts mean a little work for me to get this PR ready for merging but I'll be doing just that ASAP :)

**Comment by MartinSpeller** [comment]
[AES output does not conform to the AES57-2011 spec #362 - Assigned to pwinckles](https://trello.com/c/dzqSJYHG/60-aes-output-does-not-conform-to-the-aes57-2011-spec-362-assigned-to-pwinckles)

**Comment by ThomasEdvardsen** [comment]
Its now 4 1/2 years since @pwinckles created the pullrequest with a solution for this problem. I had to patch an local copy after a year, while waiting for this to be merged. Is there a plan for when this pull request will be merged @carlwilson?

**Review by carlwilson — APPROVED** [review]
A bit tough to resolve due to age (my bad) but this looks good to go.

**Pull request closed without merging**
